Repository HbotondS/2D-Top-down-shooter, pull requests merged in 2019-12, with the labels that each got.

#12 Refactoring
  src/2D-Top-down-shooter.cpp
  src/2D-Top-down-shooter.vcxproj
  src/2D-Top-down-shooter.vcxproj.filters
  src/Bullet.cpp
  src/Bullet.h
  src/Entity.cpp
  src/Entity.h
  src/Game.cpp
  src/Game.h
  src/GameObject.cpp
  src/GameObject.h
  src/MenuObject.cpp
  src/Player.cpp
  src/Player.h
Labels: refactor

#13 Class Diagram
  misc/ClassDiagram.jpg
Labels: documentation

#14 No title
  README.md
  src/Entity.cpp
  src/Entity.h
  src/Game.cpp
  src/Game.h
  src/Player.h
Labels: documentation, enhancement

#15 Changes on Menu / New Game
  src/2D-Top-down-shooter.cpp
  src/Character.cpp
  src/Character.h
  src/MenuObject.cpp
  src/MenuObject.h
  src/Player.cpp
  src/res/button_new-game.bmp
  src/res/player2_3.bmp
  src/res/settings.bmp
Labels: enhancement

#17 Fix issues in enemy
  src/Bullet.cpp
  src/Bullet.h
  src/Enemy.cpp
  src/Game.cpp
  src/Game.h
  src/Player.cpp
  src/res/bullet.bmp
  src/res/enemy.bmp
  src/res/enemy_2.bmp
Labels: Bugfix

#18 Refactoring nr. 2
  README.md
  misc/screenshot1.png
  src/2D-Top-down-shooter.cpp
  src/Bullet.cpp
  src/Bullet.h
  src/Enemy.cpp
  src/Enemy.h
  src/Entity.cpp
  src/Entity.h
  src/Game.cpp
  src/Game.h
  src/MenuObject.cpp
  src/MenuObject.h
  src/Player.cpp
  src/Player.h
  src/Sprite.cpp
  src/Sprite.h
Labels: documentation, refactor

#19 Settings Menu Change
  src/2D-Top-down-shooter.cpp
  src/Game.cpp
  src/Game.h
  src/MenuObject.cpp
  src/MenuObject.h
  src/Player.cpp
Labels: enhancement
